jobs:
  publish-central-and-pages:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion
        }}"
    - continue-on-error: true
      name: free disk space
      run: 'df -h

        sudo swapoff -a

        sudo rm -f /swapfile

        sudo apt clean

        docker rmi $(docker image ls -aq)

        df -h

        '
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up settings.xml for Maven Central Repository
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: '17'
        server-id: oss.sonatype.org
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        cache-name: cache-node-modules
      name: Cache node modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json')
          }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-build-${{ env.cache-name }}-

          '
    - continue-on-error: true
      name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"
        --no-transfer-progress
    - continue-on-error: true
      env:
        JDK_JAVA_OPTIONS: --add-opens java.base/java.util=ALL-UNNAMED --add-opens
          java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED
          --add-opens java.desktop/java.awt.font=ALL-UNNAMED
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      name: Publish package
      run: mvn -B deploy --no-transfer-progress -P central-deploy -DskipTests=true
    - continue-on-error: true
      name: Deploy Asciidoc docs output to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        branch: gh-pages
        clean: true
        folder: spring-boot-admin-docs/target/generated-docs
        target-folder: ${{ github.event.inputs.releaseversion }}
    - continue-on-error: true
      if: github.event.inputs.copyDocsToCurrent == 'true'
      name: Deploy Asciidoc docs output to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        branch: gh-pages
        clean: true
        folder: spring-boot-admin-docs/target/generated-docs
        target-folder: /current
  publish-github-release:
    needs: publish-central-and-pages
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: free disk space
      run: 'df -h

        sudo swapoff -a

        sudo rm -f /swapfile

        sudo apt clean

        docker rmi $(docker image ls -aq)

        df -h

        '
    - continue-on-error: true
      id: changelog
      name: Generate changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        body: 'Grab the new version from Maven central https://repo1.maven.org/maven2/de/codecentric/


          Current docs at https://codecentric.github.io/spring-boot-admin/${{ github.event.inputs.releaseversion
          }}/


          ### Things that changed in this release

          ${{ steps.changelog.outputs.changelog }}

          '
        draft: false
        prerelease: ${{ contains(github.event.inputs.releaseversion, '-') }}
        release_name: ${{ github.event.inputs.releaseversion }}
        tag_name: ${{ github.event.inputs.releaseversion }}
  set-next-snapshot-version:
    needs: publish-github-release
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set new SNAPSHOT version
      run: "mvn versions:set \"-DnewVersion=${{ github.event.inputs.releaseversion\
        \ }}\" && \\\n  mvn  versions:set -DnextSnapshot && \\\n  VERSION=$(mvn exec:exec\
        \ -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive\
        \ -q) && \\\n  mvn versions:revert && \\\n  mvn versions:set-property -Dproperty=revision\
        \  -DnewVersion=\"$VERSION\" &&\n  mvn versions:commit\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Commit new SNAPSHOT version
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: update to next SNAPSHOT version'
name: release-to-maven-central
on:
  repository_dispatch:
    types: trigger-ga___release-to-maven-central.yml
