jobs:
  semgrep:
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'renovate')
    name: semgrep/ci
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        SEMGREP_RULES: p/default
      run: semgrep ci
name: Vulnerability Scan
on:
  repository_dispatch:
    types: trigger-ga___vulnerability-scan.yml
